name: 'CMake Build'
description: 'Builds the CMake project'
inputs:
  build_dir:
    description: 'Build directory'
    required: false
    default: 'build'
  jobs:
    description: 'Number of parallel jobs to use'
    required: false
    default: '4'
runs:
  using: 'composite'
  steps:
    - name: Fix AGL framework bug on macOS
      if: runner.os == 'macOS'
      shell: bash
      run: find ${{ inputs.build_dir }} -name "link.txt" -exec sed -i '' 's/-framework AGL//g' {} + || true

    - name: Build
      shell: bash
      run: cmake --build ${{ inputs.build_dir }} --clean-first -j${{ inputs.jobs }}
