name: 'Package Windows'
description: 'Packages the Windows build into a ZIP and Installer'
inputs:
  app_version:
    description: 'Application version (e.g. v1.0.0)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: CMake Install
      shell: pwsh
      run: cmake --install build --prefix install_dir

    - name: Run Windows Deploy Qt
      shell: pwsh
      run: |
        windeployqt install_dir/bin/GarlicGUI.exe

    - name: Package Windows ZIP
      shell: pwsh
      run: |
        Compress-Archive -Path install_dir/bin/* -DestinationPath Garlic-GUI-${{ inputs.app_version }}-Windows-x64.zip

    - name: Set up Inno Setup
      shell: pwsh
      run: |
        Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "inno-setup.exe"
        .\inno-setup.exe /VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-
        $isccPath = Get-ChildItem -Path "C:\Program Files*\Inno Setup*" -Recurse -Filter "iscc.exe" -ErrorAction SilentlyContinue
        if ($isccPath) {
            $isccDir = Split-Path -Path $isccPath.FullName -Parent
            $env:Path += ";$isccDir"
            Write-Output "Inno Setup is installed at: $isccDir"
            echo "ISCC_DIR=$isccDir" >> $env:GITHUB_ENV
        } else {
            Write-Output "Inno Setup is not installed."
            exit 1
        }

    - name: Create Windows Installer
      shell: pwsh
      run: |
        $env:Path += ";$env:ISCC_DIR"
        $version = "${{ inputs.app_version }}".TrimStart('v')
        iscc /DAppVersion=$version scripts/windows/installer.iss
        Move-Item scripts/windows/Output/Garlic-GUI-Windows-installer-$version.exe Garlic-GUI-${{ inputs.app_version }}-Windows-x64-installer.exe
