name: 'CMake Install'
description: 'Installs the CMake project'
inputs:
  build_dir:
    description: 'Build directory'
    required: false
    default: 'build'
  install_prefix:
    description: 'Installation prefix directory'
    required: false
    default: 'install_dir'
runs:
  using: 'composite'
  steps:
    - name: Install
      shell: bash
      run: cmake --install ${{ inputs.build_dir }} --prefix ${{ inputs.install_prefix }}
