name: 'Upload Artifacts'
description: 'Uploads build artifacts to GitHub Actions'
inputs:
  name:
    description: 'Artifact name'
    required: true
  path:
    description: 'File, directory or wildcard pattern to upload'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Upload Artifacts
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
