name: Release Build

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  APP_VERSION: ${{ github.ref_name }}
  QT_VERSION: "6.10.3"

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7

      - name: Install Qt (Windows)
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          target: "desktop"
          arch: "win64_mingw"
          tools: "tools_mingw1310"

      - name: Configure CMake (Windows)
        shell: pwsh
        run: |
            Write-Host "QT_ROOT_DIR: $env:QT_ROOT_DIR"

            $gcc = Get-Command gcc.exe -ErrorAction Stop
            $gpp = Get-Command g++.exe -ErrorAction Stop
            $make = Get-Command mingw32-make.exe -ErrorAction Stop

            Write-Host "gcc:  $($gcc.Source)"
            Write-Host "g++:  $($gpp.Source)"
            Write-Host "make: $($make.Source)"

            $env:CC = $gcc.Source
            $env:CXX = $gpp.Source

            if (Test-Path build) { Remove-Item -Recurse -Force build }

            cmake -B build -S . -G "MinGW Makefiles" `
              -DCMAKE_PREFIX_PATH="$env:QT_ROOT_DIR" `
              -DGARLIC_STATIC_QT=ON `
              -DCMAKE_BUILD_TYPE=Release `
              -DCMAKE_CXX_STANDARD=17 `
              -DCMAKE_EXE_LINKER_FLAGS="-Wl,--allow-multiple-definition" `
              -DCMAKE_C_COMPILER="$env:CC" `
              -DCMAKE_CXX_COMPILER="$env:CXX" `
              -DCMAKE_MAKE_PROGRAM="$($make.Source)"

      - name: Build
        run: cmake --build build --clean-first -j4

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v7
        with:
          name: windows-artifacts
          path: build/GarlicGUI.exe

  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          target: "desktop"

      - name: Configure CMake
        run: cmake -B build -S . -DGARLIC_STATIC_QT=ON -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --clean-first -j4

      - name: Upload Linux Executable
        uses: actions/upload-artifact@v7
        with:
          name: linux-artifacts
          path: build/GarlicGUI

  build-macos-intel:
    runs-on: macos-26-intel
    steps:
      - uses: actions/checkout@v7

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          target: "desktop"

      - name: Configure CMake
        run: cmake -B build -S . -DGARLIC_STATIC_QT=ON -DCMAKE_BUILD_TYPE=Release

      - name: Fix AGL framework bug on macOS
        run: find build -name "link.txt" -exec sed -i '' 's/-framework AGL//g' {} +

      - name: Build
        run: cmake --build build --clean-first -j4

      - name: Package and Upload
        run: tar czf Garlic-GUI-${{ env.APP_VERSION }}-MacOS-intel-x64.tar.gz -C build GarlicGUI.app

      - name: Upload MacOS Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: macos-intel-artifacts
          path: Garlic-GUI-${{ env.APP_VERSION }}-MacOS-intel-x64.tar.gz

  build-macos:
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v7

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          target: "desktop"

      - name: Configure CMake
        run: cmake -B build -S . -DGARLIC_STATIC_QT=ON -DCMAKE_BUILD_TYPE=Release

      - name: Fix AGL framework bug on macOS
        run: find build -name "link.txt" -exec sed -i '' 's/-framework AGL//g' {} +

      - name: Build
        run: cmake --build build --clean-first -j4

      - name: Package and Upload
        run: tar czf Garlic-GUI-${{ env.APP_VERSION }}-MacOS-arm64.tar.gz -C build GarlicGUI.app

      - name: Upload MacOS Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: macos-artifacts
          path: Garlic-GUI-${{ env.APP_VERSION }}-MacOS-arm64.tar.gz

  release:
    needs: [build-windows, build-linux, build-macos, build-macos-intel]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Download Windows Artifacts
        uses: actions/download-artifact@v8
        with:
          name: windows-artifacts
          path: artifacts/

      - name: Download Linux Artifacts
        uses: actions/download-artifact@v8
        with:
          name: linux-artifacts
          path: artifacts/

      - name: Download MacOS Artifacts
        uses: actions/download-artifact@v8
        with:
          name: macos-artifacts
          path: artifacts/

      - name: Download MacOS (Intel) Artifacts
        uses: actions/download-artifact@v8
        with:
          name: macos-intel-artifacts
          path: artifacts/

      - name: List downloaded artifacts
        run: ls -l artifacts/

      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          tag_name: ${{ env.APP_VERSION }}
          name: Release ${{ env.APP_VERSION }}
          draft: false
          prerelease: false
          files: |
            artifacts/GarlicGUI.exe
            artifacts/GarlicGUI
            artifacts/Garlic-GUI-${{ env.APP_VERSION }}-MacOS-arm64.tar.gz
            artifacts/Garlic-GUI-${{ env.APP_VERSION }}-MacOS-intel-x64.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
